CREATE TABLE IF NOT EXISTS USER_WORK_EXPERIENCE (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    COMPANY_NAME VARCHAR(255),
    DESIGNATION VARCHAR(255),
    START_DATE TIMESTAMP WITH TIME ZONE,
    END_DATE TIMESTAMP WITH TIME ZONE,
    STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT CHK_USER_WORK_EXPERIENCE_STATUS CHECK (STATUS IN ('AI_PARSED', 'USER_REVIEWED')),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_USER_WORK_EXPERIENCE_USER_ID ON USER_WORK_EXPERIENCE(USER_ID);

CREATE TABLE IF NOT EXISTS USER_EDUCATION (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    INSTITUTION_NAME VARCHAR(255),
    DEGREE VARCHAR(255),
    START_DATE TIMESTAMP WITH TIME ZONE,
    END_DATE TIMESTAMP WITH TIME ZONE,
    STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT CHK_USER_EDUCATION_STATUS CHECK (STATUS IN ('AI_PARSED', 'USER_REVIEWED')),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_USER_EDUCATION_USER_ID ON USER_EDUCATION(USER_ID);

CREATE TABLE IF NOT EXISTS USER_SKILL (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    SKILL_ID BIGINT NOT NULL,
    PROFICIENCY_LEVEL VARCHAR(50),
    STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT CHK_USER_SKILL_STATUS CHECK (STATUS IN ('AI_PARSED', 'USER_REVIEWED')),
    CONSTRAINT CHK_USER_SKILL_PROFICIENCY_LEVEL CHECK (PROFICIENCY_LEVEL IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (SKILL_ID) REFERENCES SKILLS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_USER_SKILL_USER_ID ON USER_SKILL(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_USER_SKILL_SKILL_ID ON USER_SKILL(SKILL_ID);