ALTER TABLE USERS
    ADD COLUMN IF NOT EXISTS SUSPENDED BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS ADMIN_USER_ACTIONS (
    ID BIGSERIAL PRIMARY KEY,
    TARGET_USER_ID BIGINT NOT NULL,
    ADMIN_USER_ID BIGINT NOT NULL,
    ACTION VARCHAR(20) NOT NULL,
    COMMENT VARCHAR(1000) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ADMIN_ACTION_TARGET FOREIGN KEY (TARGET_USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_ADMIN_ACTION_ADMIN FOREIGN KEY (ADMIN_USER_ID) REFERENCES USERS(ID),
    CONSTRAINT CHK_ADMIN_ACTION CHECK (ACTION IN ('SUSPEND', 'RESTORE'))
);

