CREATE TABLE IF NOT EXISTS CATEGORIES (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);