CREATE TABLE IF NOT EXISTS TOKENS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TOKEN VARCHAR(512) NOT NULL,
    TOKEN_TYPE VARCHAR(20) NOT NULL,
    REVOKED BOOLEAN DEFAULT FALSE NOT NULL,
    EXPIRY_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_TOKEN_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_TOKEN_TYPE CHECK (TOKEN_TYPE IN ('BEARER', 'REFRESH'))
);