CREATE TABLE IF NOT EXISTS USER_CV (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TITLE VARCHAR(32) NOT NULL,
    FILE_TYPE VARCHAR(10) NOT NULL,
    FILE_DATA BYTEA NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    UPLOADED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CV_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_CV_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT CHK_FILE_TYPE CHECK (FILE_TYPE IN ('PDF', 'DOCX'))
);