CREATE TABLE IF NOT EXISTS APPLICATIONS (
    ID BIGSERIAL PRIMARY KEY,
    STATUS VARCHAR(20) NOT NULL,
    COMMENT TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    JOB_OFFER_ID BIGINT NOT NULL,
    APPLICANT_ID BIGINT NOT NULL,
    CV_ID BIGINT NOT NULL,
    CONSTRAINT FK_JOB_OFFER_ID FOREIGN KEY (JOB_OFFER_ID) REFERENCES JOB_OFFERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_APPLICANT_ID FOREIGN KEY (APPLICANT_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CV_ID FOREIGN KEY (CV_ID) REFERENCES USER_CV(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_APPLICATION_STATUS CHECK (STATUS IN ('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN'))
);