CREATE TABLE IF NOT EXISTS SKILLS (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    TYPE VARCHAR(32) NOT NULL,
    EMBEDDING TEXT NOT NULL,
    CONSTRAINT CHK_SKILL_TYPE CHECK (TYPE IN ('TECHNICAL', 'SOFT'))
);