INSERT INTO SKILLS (ID, NAME, TYPE) VALUES
    -- Programming languages
    (1, 'Java', 'TECHNICAL'),
    (2, 'Python', 'TECHNICAL'),
    (3, 'C#', 'TECHNICAL'),
    (4, 'C++', 'TECHNICAL'),
    (5, 'C', 'TECHNICAL'),
    (6, 'JavaScript', 'TECHNICAL'),
    (7, 'TypeScript', 'TECHNICAL'),
    (8, 'Go', 'TECHNICAL'),
    (9, 'Rust', 'TECHNICAL'),
    (10, 'Kotlin', 'TECHNICAL'),
    (11, 'Swift', 'TECHNICAL'),
    (12, 'Ruby', 'TECHNICAL'),
    (13, 'PHP', 'TECHNICAL'),
    (14, 'Scala', 'TECHNICAL'),
    (15, 'R', 'TECHNICAL'),
    (16, 'Dart', 'TECHNICAL'),
    (17, 'Objective-C', 'TECHNICAL'),
    (18, 'Shell Scripting', 'TECHNICAL'),
    (19, 'Bash', 'TECHNICAL'),
    (20, 'PowerShell', 'TECHNICAL'),
    -- Web fundamentals
    (21, 'HTML', 'TECHNICAL'),
    (22, 'CSS', 'TECHNICAL'),
    (23, 'Sass', 'TECHNICAL'),
    (24, 'Less', 'TECHNICAL'),
    -- Frontend frameworks/libraries
    (25, 'React', 'TECHNICAL'),
    (26, 'Angular', 'TECHNICAL'),
    (27, 'Vue.js', 'TECHNICAL'),
    (28, 'Svelte', 'TECHNICAL'),
    (29, 'Next.js', 'TECHNICAL'),
    (30, 'Nuxt.js', 'TECHNICAL'),
    (31, 'Redux', 'TECHNICAL'),
    (32, 'RxJS', 'TECHNICAL'),
    (33, 'Webpack', 'TECHNICAL'),
    (34, 'Vite', 'TECHNICAL'),
    (35, 'Tailwind CSS', 'TECHNICAL'),
    (36, 'Bootstrap', 'TECHNICAL'),
    (37, 'Material UI', 'TECHNICAL'),
    -- Backend frameworks
    (38, 'Spring Framework', 'TECHNICAL'),
    (39, 'Spring Boot', 'TECHNICAL'),
    (40, '.NET', 'TECHNICAL'),
    (41, 'ASP.NET Core', 'TECHNICAL'),
    (42, 'Node.js', 'TECHNICAL'),
    (43, 'Express.js', 'TECHNICAL'),
    (44, 'NestJS', 'TECHNICAL'),
    (45, 'Django', 'TECHNICAL'),
    (46, 'Flask', 'TECHNICAL'),
    (47, 'FastAPI', 'TECHNICAL'),
    (48, 'Ruby on Rails', 'TECHNICAL'),
    (49, 'Laravel', 'TECHNICAL'),
    (50, 'Symfony', 'TECHNICAL'),
    (51, 'Golang Gin', 'TECHNICAL'),
    -- Mobile & cross-platform
    (52, 'Android', 'TECHNICAL'),
    (53, 'iOS', 'TECHNICAL'),
    (54, 'React Native', 'TECHNICAL'),
    (55, 'Flutter', 'TECHNICAL'),
    (56, 'Xamarin', 'TECHNICAL'),
    -- Databases & storage
    (57, 'PostgreSQL', 'TECHNICAL'),
    (58, 'MySQL', 'TECHNICAL'),
    (59, 'MariaDB', 'TECHNICAL'),
    (60, 'SQL Server', 'TECHNICAL'),
    (61, 'Oracle Database', 'TECHNICAL'),
    (62, 'SQLite', 'TECHNICAL'),
    (63, 'MongoDB', 'TECHNICAL'),
    (64, 'Redis', 'TECHNICAL'),
    (65, 'Elasticsearch', 'TECHNICAL'),
    (66, 'Cassandra', 'TECHNICAL'),
    (67, 'DynamoDB', 'TECHNICAL'),
    -- Data & streaming
    (68, 'Apache Kafka', 'TECHNICAL'),
    (69, 'RabbitMQ', 'TECHNICAL'),
    (70, 'ActiveMQ', 'TECHNICAL'),
    (71, 'Apache Spark', 'TECHNICAL'),
    (72, 'Hadoop', 'TECHNICAL'),
    (73, 'Apache Hive', 'TECHNICAL'),
    (74, 'Apache Airflow', 'TECHNICAL'),
    (75, 'Snowflake', 'TECHNICAL'),
    (76, 'BigQuery', 'TECHNICAL'),
    (77, 'Databricks', 'TECHNICAL'),
    -- Cloud & DevOps
    (78, 'AWS', 'TECHNICAL'),
    (79, 'Azure', 'TECHNICAL'),
    (80, 'Google Cloud', 'TECHNICAL'),
    (81, 'Docker', 'TECHNICAL'),
    (82, 'Kubernetes', 'TECHNICAL'),
    (83, 'Terraform', 'TECHNICAL'),
    (84, 'Ansible', 'TECHNICAL'),
    (85, 'Pulumi', 'TECHNICAL'),
    (86, 'Helm', 'TECHNICAL'),
    (87, 'Jenkins', 'TECHNICAL'),
    (88, 'GitLab CI', 'TECHNICAL'),
    (89, 'GitHub Actions', 'TECHNICAL'),
    (90, 'CircleCI', 'TECHNICAL'),
    -- Build & package managers
    (91, 'Maven', 'TECHNICAL'),
    (92, 'Gradle', 'TECHNICAL'),
    (93, 'Ant', 'TECHNICAL'),
    (94, 'npm', 'TECHNICAL'),
    (95, 'Yarn', 'TECHNICAL'),
    (96, 'pnpm', 'TECHNICAL'),
    -- Testing & QA
    (97, 'JUnit', 'TECHNICAL'),
    (98, 'TestNG', 'TECHNICAL'),
    (99, 'Mockito', 'TECHNICAL'),
    (100, 'Selenium', 'TECHNICAL'),
    (101, 'Cypress', 'TECHNICAL'),
    (102, 'Playwright', 'TECHNICAL'),
    (103, 'Jest', 'TECHNICAL'),
    (104, 'Mocha', 'TECHNICAL'),
    (105, 'Chai', 'TECHNICAL'),
    (106, 'PyTest', 'TECHNICAL'),
    (107, 'RSpec', 'TECHNICAL'),
    -- APIs & protocols
    (108, 'REST', 'TECHNICAL'),
    (109, 'GraphQL', 'TECHNICAL'),
    (110, 'gRPC', 'TECHNICAL'),
    (111, 'WebSockets', 'TECHNICAL'),
    -- Security & auth
    (112, 'OAuth 2.0', 'TECHNICAL'),
    (113, 'OpenID Connect', 'TECHNICAL'),
    (114, 'JWT', 'TECHNICAL'),
    (115, 'SAML', 'TECHNICAL'),
    (116, 'TLS/SSL', 'TECHNICAL'),
    -- Observability & monitoring
    (117, 'Prometheus', 'TECHNICAL'),
    (118, 'Grafana', 'TECHNICAL'),
    (119, 'ELK Stack', 'TECHNICAL'),
    (120, 'OpenTelemetry', 'TECHNICAL'),
    (121, 'Datadog', 'TECHNICAL'),
    (122, 'New Relic', 'TECHNICAL'),
    -- Configuration & messaging
    (123, 'Nginx', 'TECHNICAL'),
    (124, 'Apache HTTP Server', 'TECHNICAL'),
    (125, 'HAProxy', 'TECHNICAL'),
    (126, 'Consul', 'TECHNICAL'),
    (127, 'Etcd', 'TECHNICAL'),
    -- UI/UX & design tools
    (128, 'Figma', 'TECHNICAL'),
    (129, 'Adobe XD', 'TECHNICAL'),
    -- Other technical
    (130, 'Regex', 'TECHNICAL'),
    (131, 'UML', 'TECHNICAL'),
    (132, 'Linux', 'TECHNICAL'),
    (133, 'Windows', 'TECHNICAL'),
    (134, 'macOS', 'TECHNICAL'),
    (135, 'Git', 'TECHNICAL'),
    (136, 'SVN', 'TECHNICAL'),
    -- Soft skills
    (137, 'Communication', 'SOFT'),
    (138, 'Teamwork', 'SOFT'),
    (139, 'Leadership', 'SOFT'),
    (140, 'Problem Solving', 'SOFT'),
    (141, 'Critical Thinking', 'SOFT'),
    (142, 'Time Management', 'SOFT'),
    (143, 'Adaptability', 'SOFT'),
    (144, 'Creativity', 'SOFT'),
    (145, 'Empathy', 'SOFT'),
    (146, 'Negotiation', 'SOFT'),
    (147, 'Conflict Resolution', 'SOFT'),
    (148, 'Mentoring', 'SOFT'),
    (149, 'Presentation Skills', 'SOFT'),
    (150, 'Stakeholder Management', 'SOFT'),
    (151, 'Product Sense', 'SOFT'),
    (152, 'Attention to Detail', 'SOFT'),
    (153, 'Accountability', 'SOFT'),
    (154, 'Decision Making', 'SOFT'),
    (155, 'Collaboration', 'SOFT'),
    (156, 'Ownership', 'SOFT');