CREATE TABLE IF NOT EXISTS SKILL_ALIASES (
    ID BIGSERIAL PRIMARY KEY,
    SKILL_ID BIGINT NOT NULL,
    ALIAS VARCHAR(64) NOT NULL,
    CONSTRAINT FK_SKILL_ALIAS_SKILL_ID FOREIGN KEY (SKILL_ID) REFERENCES SKILLS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_SKILL_ALIASES_SKILL_ID ON SKILL_ALIASES(SKILL_ID);