CREATE TABLE IF NOT EXISTS JOB_SKILLS (
    ID BIGSERIAL PRIMARY KEY,
    JOB_OFFER_ID BIGINT NOT NULL,
    SKILL_ID BIGINT NOT NULL,
    EXPECTED_PROFICIENCY VARCHAR(20) NOT NULL,
    CONSTRAINT CHK_PROFICIENCY_LEVEL CHECK (EXPECTED_PROFICIENCY IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')),
    CONSTRAINT FK_JOB_SKILL_JOB_OFFER_ID FOREIGN KEY (JOB_OFFER_ID) REFERENCES JOB_OFFERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_JOB_SKILL_SKILL_ID FOREIGN KEY (SKILL_ID) REFERENCES SKILLS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_JOB_SKILLS_JOB_OFFER_ID ON JOB_SKILLS(JOB_OFFER_ID);
CREATE INDEX IF NOT EXISTS IDX_JOB_SKILLS_SKILL_ID ON JOB_SKILLS(SKILL_ID);