INSERT INTO USER_SKILL (USER_ID, SKILL_ID, PROFICIENCY_LEVEL, STATUS)
VALUES
       (4, 25, 'ADVANCED', 'USER_REVIEWED'),
       (4, 6, 'ADVANCED', 'USER_REVIEWED'),
       (4, 7, 'INTERMEDIATE', 'USER_REVIEWED'),
       (4, 31, 'INTERMEDIATE', 'USER_REVIEWED'),
       (4, 21, 'ADVANCED', 'USER_REVIEWED'),
       (4, 22, 'ADVANCED', 'USER_REVIEWED'),
       (4, 35, 'INTERMEDIATE', 'USER_REVIEWED'),
       (4, 103, 'INTERMEDIATE', 'USER_REVIEWED'),
       (6, 1, 'ADVANCED', 'USER_REVIEWED'),
       (6, 39, 'ADVANCED', 'USER_REVIEWED'),
       (6, 57, 'ADVANCED', 'USER_REVIEWED'),
       (6, 108, 'INTERMEDIATE', 'USER_REVIEWED'),
       (6, 91, 'INTERMEDIATE', 'USER_REVIEWED'),
       (6, 135, 'ADVANCED', 'USER_REVIEWED'),
       (7, 10, 'ADVANCED', 'USER_REVIEWED'),
       (7, 52, 'ADVANCED', 'USER_REVIEWED'),
       (7, 11, 'INTERMEDIATE', 'USER_REVIEWED'),
       (7, 53, 'INTERMEDIATE', 'USER_REVIEWED'),
       (7, 54, 'INTERMEDIATE', 'USER_REVIEWED'),
       (7, 57, 'INTERMEDIATE', 'USER_REVIEWED'),
       (7, 135, 'ADVANCED', 'USER_REVIEWED');

