INSERT INTO JOB_OFFERS (TITLE, DESCRIPTION, COMPANY, SALARY, YEARS_OF_EXPERIENCE,
                        WORK_TYPE, LOCATION, CONTACT_EMAIL, CONTACT_PHONE,
                        STATUS, CREATED_AT, UPDATED_AT, CATEGORY_ID, CREATOR_ID)
VALUES ('Junior Java Developer', 'We are looking for a passionate Junior Java Developer to join our IT team.',
        'TechCorp', 50000.00, 1, 'ON_SITE', 'New York, NY', 'hr@techcorp.com', '+1234567890', 'OPEN',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
       ('Frontend Engineer', 'Seeking a Frontend Engineer skilled in React and TypeScript.', 'Innovatech', 55000.00, 2,
        'ON_SITE', 'San Francisco, CA', 'jobs@innovatech.com', '+1987654321', 'OPEN', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 1, 1),
       ('Backend Developer', 'Backend Developer needed to work on microservices and APIs.', 'SoftSolutions', 60000.00,
        3, 'ON_SITE', 'Austin, TX', 'careers@softsolutions.com', '+1123456789', 'OPEN', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 1, 1),
       ('Full Stack Developer', 'Full Stack Developer to handle both frontend and backend tasks.', 'DevWorks', 65000.00,
        2, 'ON_SITE', 'Seattle, WA', 'talent@devworks.com', '+1098765432', 'OPEN', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 1, 1),
       ('IT Support Specialist', 'Provide IT support and troubleshooting for company systems.', 'NetTech', 45000.00, 1,
        'ON_SITE', 'Chicago, IL', 'support@nettech.com', '+1230984567', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
        1, 1),
       ('Data Analyst', 'Looking for a Data Analyst to interpret data and provide actionable insights.', 'DataSense',
        58000.00, 2, 'ON_SITE', 'Boston, MA', 'jobs@datasense.com', '+12135551234', 'OPEN', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 1, 1),
       ('DevOps Engineer', 'Responsible for CI/CD pipelines and cloud infrastructure management.', 'CloudWorks',
        70000.00, 3, 'ON_SITE', 'Denver, CO', 'hr@cloudworks.com', '+13035559876', 'OPEN', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 1, 1),
       ('QA Tester', 'Ensure software quality through testing and bug reporting.', 'SoftSolutions', 48000.00, 1,
        'ON_SITE', 'Austin, TX', 'qa@softsolutions.com', '+1123456789', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1,
        1),
       ('Mobile App Developer', 'Develop and maintain mobile applications for iOS and Android.', 'AppMasters', 62000.00,
        2, 'ON_SITE', 'Los Angeles, CA', 'careers@appmasters.com', '+13105551234', 'OPEN', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 1, 1),
       ('Database Administrator', 'Manage and optimize company databases and ensure security.', 'DBPro', 67000.00, 3,
        'ON_SITE', 'Atlanta, GA', 'hr@dbpro.com', '+14045551234', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
       ('Cybersecurity Analyst', 'Monitor security systems and respond to threats.', 'SecureIT', 72000.00, 3, 'ON_SITE',
        'Washington, DC', 'security@secureit.com', '+12025551234', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
       ('Cloud Solutions Architect', 'Design and implement scalable cloud solutions.', 'CloudWorks', 95000.00, 5,
        'ON_SITE', 'Denver, CO', 'jobs@cloudworks.com', '+13035559876', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1,
        1),
       ('Machine Learning Engineer', 'Develop ML models and pipelines for predictive analytics.', 'AI Labs', 90000.00,
        3, 'ON_SITE', 'San Francisco, CA', 'ml@ailabs.com', '+1987654321', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
        1, 1),
       ('System Administrator', 'Maintain IT infrastructure and provide technical support.', 'NetTech', 52000.00, 2,
        'ON_SITE', 'Chicago, IL', 'support@nettech.com', '+1230984567', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1,
        1),
       ('UI/UX Designer', 'Design intuitive interfaces and user experiences for web and mobile apps.', 'DesignHub',
        60000.00, 2, 'ON_SITE', 'New York, NY', 'jobs@designhub.com', '+1234567890', 'OPEN', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 1, 1),
       ('Technical Writer', 'Create clear technical documentation and manuals.', 'DocuTech', 50000.00, 1, 'ON_SITE',
        'Boston, MA', 'hr@docutech.com', '+12135551234', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
       ('AI Researcher', 'Conduct research on AI algorithms and technologies.', 'AI Labs', 98000.00, 4, 'ON_SITE',
        'San Francisco, CA', 'ml@ailabs.com', '+1987654321', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
       ('Network Engineer', 'Design, implement, and maintain network infrastructure.', 'NetWorks', 68000.00, 3,
        'ON_SITE', 'Seattle, WA', 'network@networks.com', '+1098765432', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
        1, 1),
       ('Product Manager', 'Lead product development and coordinate with engineering teams.', 'Innovatech', 90000.00, 4,
        'ON_SITE', 'San Francisco, CA', 'jobs@innovatech.com', '+1987654321', 'OPEN', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 1, 1),
       ('Software Architect', 'Design software architecture and provide technical guidance.', 'DevWorks', 105000.00, 5,
        'ON_SITE', 'Seattle, WA', 'talent@devworks.com', '+1098765432', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1,
        1),
       ('Business Analyst', 'Analyze business processes and provide data-driven recommendations.', 'BizSolutions',
        60000.00, 2, 'ON_SITE', 'Chicago, IL', 'hr@bizsolutions.com', '+1230984567', 'OPEN', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 1, 1),
       ('Scrum Master', 'Facilitate agile processes and team coordination.', 'AgileTech', 75000.00, 3, 'ON_SITE',
        'New York, NY', 'hr@agiletech.com', '+1234567890', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
       ('Site Reliability Engineer', 'Ensure reliability and uptime of production systems.', 'CloudWorks', 88000.00, 4,
        'ON_SITE', 'Denver, CO', 'jobs@cloudworks.com', '+13035559876', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1,
        1),
       ('AI Product Engineer', 'Integrate AI solutions into existing products.', 'AI Labs', 92000.00, 3, 'ON_SITE',
        'San Francisco, CA', 'ml@ailabs.com', '+1987654321', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1),
       ('Technical Support Engineer', 'Provide technical assistance for software and hardware issues.', 'NetTech',
        48000.00, 1, 'ON_SITE', 'Chicago, IL', 'support@nettech.com', '+1230984567', 'OPEN', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP, 1, 1),
       ('Embedded Systems Engineer', 'Develop embedded systems for IoT devices.', 'TechCorp', 78000.00, 3, 'ON_SITE',
        'New York, NY', 'hr@techcorp.com', '+1234567890', 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1);