INSERT INTO APPLICATIONS(STATUS, COMMENT, JOB_OFFER_ID, APPLICANT_ID)
VALUES ('PENDING', 'I am very interested in this position and believe my skills are a great match.', 1, 2),
       ('PENDING', 'Looking forward to contributing to your team with my frontend expertise.', 2, 2),
       ('PENDING', 'Excited about the opportunity to work on backend systems at SoftSolutions.', 3, 2),
       ('WITHDRAWN', 'Looking forward to contributing to your team with my frontend expertise.', 4, 2),
       ('WITHDRAWN', 'Excited about the opportunity to work on backend systems at SoftSolutions.', 5, 2),
       ('PENDING', 'Looking forward to contributing to your team with my frontend expertise.', 6, 2),
       ('REJECTED', 'Excited about the opportunity to work on backend systems at SoftSolutions.', 7, 2),
       ('ACCEPTED', 'Looking forward to contributing to your team with my frontend expertise.', 8, 2),
       ('PENDING', 'Excited about the opportunity to work on backend systems at SoftSolutions.', 9, 2),
       ('PENDING', 'Looking forward to contributing to your team with my frontend expertise.', 10, 2),
       ('ACCEPTED', 'Excited about the opportunity to work on backend systems at SoftSolutions.', 11, 2),
       ('PENDING', 'Looking forward to contributing to your team with my frontend expertise.', 12, 2),
       ('ACCEPTED', 'Excited about the opportunity to work on backend systems at SoftSolutions.', 13, 2),
       ('REJECTED', 'Looking forward to contributing to your team with my frontend expertise.', 14, 2),
       ('REJECTED', 'Excited about the opportunity to work on backend systems at SoftSolutions.', 15, 2);