INSERT INTO APPLICATIONS(STATUS, COMMENT, JOB_OFFER_ID, APPLICANT_ID)
VALUES
('PENDING', 'Interested in the role and confident I can deliver quickly.', 1, 4),
('PENDING', 'Motivated to join and contribute to the team goals.', 2, 4),
('WITHDRAWN', 'Accepted another offer but appreciated the opportunity.', 3, 4),
('PENDING', 'Excited to apply and ready to start as soon as needed.', 4, 4),
('PENDING', 'Strong interest in the product and the mission.', 5, 4),
('REJECTED', 'Thank you for the consideration and feedback.', 6, 4),
('PENDING', 'I enjoy solving problems like the ones described.', 7, 4),
('PENDING', 'I am confident I can ramp up fast and add value.', 8, 4),
('ACCEPTED', 'Excited to join and start on the agreed date.', 9, 4),
('PENDING', 'Eager to contribute and grow with the company.', 10, 4),
('PENDING', 'I value collaboration and continuous improvement.', 11, 4),
('REJECTED', 'Understood, please keep me in mind for future roles.', 12, 4),
('PENDING', 'I can support the team and deliver quality work.', 13, 4),
('PENDING', 'Looking for a role where I can make impact.', 14, 4),
('WITHDRAWN', 'Decided to pause my search for personal reasons.', 15, 4),
('PENDING', 'Interested in contributing to a reliable platform.', 16, 4),
('PENDING', 'I can help improve performance and stability.', 17, 4),
('PENDING', 'Motivated to work on scalable systems.', 18, 4),
('PENDING', 'Excited about the stack and team culture.', 19, 4),
('ACCEPTED', 'Happy to move forward and complete onboarding steps.', 20, 4),
('PENDING', 'I enjoy building data pipelines and tools.', 21, 4),
('PENDING', 'Passionate about MLOps and production quality.', 22, 4),
('PENDING', 'Detail oriented and thorough in testing.', 23, 4),
('PENDING', 'Security focused mindset and practical approach.', 24, 4),
('PENDING', 'Cloud platform work aligns with my experience.', 25, 4),
('PENDING', 'Excited to apply and learn from the team.', 4, 6),
('PENDING', 'Looking forward to collaborating and delivering.', 5, 6),
('PENDING', 'Interested in the responsibilities described.', 6, 6),
('PENDING', 'I enjoy work like this and want to join.', 7, 7),
('PENDING', 'Ready to contribute and grow in this role.', 8, 7),
('PENDING', 'Skilled in the tools mentioned in the post.', 9, 7),
('PENDING', 'Looking for a role with real impact.', 10, 8),
('PENDING', 'I value teamwork and clean delivery.', 11, 8),
('PENDING', 'Motivated to take on the listed duties.', 12, 8),
('PENDING', 'I can add value quickly in this role.', 13, 9),
('PENDING', 'Strong interest in the company and work.', 14, 9),
('PENDING', 'Good match with my recent projects.', 15, 9),
('PENDING', 'I am excited to apply to this opening.', 16, 10),
('PENDING', 'Ready to help the team reach goals.', 17, 10),
('PENDING', 'Interested in the stack and challenges.', 18, 10);
