INSERT INTO JOB_SKILLS (JOB_OFFER_ID, SKILL_ID, EXPECTED_PROFICIENCY)
VALUES (1, 1, 'INTERMEDIATE'),
       (1, 38, 'BEGINNER'),
       (1, 39, 'BEGINNER'),
       (1, 57, 'BEGINNER'),
       (1, 108, 'BEGINNER'),
       (1, 135, 'BEGINNER');

INSERT INTO JOB_SKILLS (JOB_OFFER_ID, SKILL_ID, EXPECTED_PROFICIENCY)
VALUES (2, 6, 'ADVANCED'),
       (2, 7, 'ADVANCED'),
       (2, 25, 'ADVANCED'),
       (2, 21, 'ADVANCED'),
       (2, 22, 'ADVANCED'),
       (2, 35, 'INTERMEDIATE'),
       (2, 33, 'INTERMEDIATE'),
       (2, 135, 'INTERMEDIATE');

INSERT INTO JOB_SKILLS (JOB_OFFER_ID, SKILL_ID, EXPECTED_PROFICIENCY)
VALUES (3, 2, 'ADVANCED'),
       (3, 47, 'INTERMEDIATE'),
       (3, 42, 'INTERMEDIATE'),
       (3, 63, 'INTERMEDIATE'),
       (3, 57, 'ADVANCED'),
       (3, 108, 'ADVANCED'),
       (3, 81, 'BEGINNER');

INSERT INTO JOB_SKILLS (JOB_OFFER_ID, SKILL_ID, EXPECTED_PROFICIENCY)
VALUES (4, 6, 'ADVANCED'),
       (4, 25, 'INTERMEDIATE'),
       (4, 42, 'INTERMEDIATE'),
       (4, 43, 'INTERMEDIATE'),
       (4, 57, 'INTERMEDIATE'),
       (4, 108, 'ADVANCED'),
       (4, 81, 'INTERMEDIATE'),
       (4, 135, 'INTERMEDIATE');

INSERT INTO JOB_SKILLS (JOB_OFFER_ID, SKILL_ID, EXPECTED_PROFICIENCY)
VALUES (5, 132, 'INTERMEDIATE'),
       (5, 133, 'INTERMEDIATE'),
       (5, 18, 'BEGINNER'),
       (5, 137, 'ADVANCED'),
       (5, 140, 'ADVANCED'),
       (5, 152, 'INTERMEDIATE');

